version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./PETPAL_DB/Scripts/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      # - ./PETPAL_DB/data/csv:/var/lib/postgresql/csv

    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db/mydb
      SSL_ENABLED: true
      SSL_DISABLE: False
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
